### ISSUE TITLE
ES6 Target and Module

### ISSUE THREAD

**Issue by eugenkiss** [mobxjs/mobx-react-typescript-boilerplate#3]
When specifying the value `"es6"` for `compilerOptions.target` and `compilerOptions.module` in `tsconfig.json` and using babel for es6 to es5 conversion I see the following error messages.

```
ERROR in ./src/index.tsx
(3,26): error TS2307: Cannot find module 'mobx'.

ERROR in ./src/index.tsx
(4,24): error TS2307: Cannot find module 'mobx-react'.

ERROR in ./src/index.tsx
(5,22): error TS2307: Cannot find module 'mobx-react-devtools'.
```

The project itself runs fine though. Do you have any suggestions how to fix this problem?

**Comment by mweststrate** [comment]
Yes that is because typescript will only resolve typings "the node way" if you specify common js as target, in which case it will pick up the typings fields of the package.json files. But maybe one of these work arounds fixes the issue:

It might help to set the compiler flag `moduleResolution` to `node`.

It might be possible to work around this issue by using old fashioned `/// <reference path` etc to the relevant `.d.ts` files in the module directories of each of these packages. I'm not entirely sure whether that works because those reference path tags probably expect ambient module declarations.

Best is to use `commonjs` as module target because they are common js modules.

And this should work at least: `const mobx = require("mobx")`. You loose the typings but at least everything should compile.

**Comment by eugenkiss** [comment]
Thanks a lot for your suggestions. I tried to make my project compile with `commonjs` as a module target but to no avail. Eventually, I settled on using mobx without typing information (essentially `const mobx = require("mobx")`.

**Comment by SophieLeeroy** [comment]
I know its old but i've had to face the same issue and finally i found the solution: mobx and mox-react has to be installed (and saved) as dependecies --save, not devDependecies

**Comment by Epskampie** [comment]
@SophieLeeroy  that's might just be because you got newer versions that way.

**Comment by tonghae** [comment]
`"allowJs": true` helped in my case
